name: nutribem
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Banco de dados
  sqflite: ^2.4.2+1
  path: ^1.9.1
  sqflite_common_ffi: ^2.4.0+3
  sqflite_common_ffi_web: ^0.4.5+3

  # Datas
  intl: ^0.20.2

  # Notificações
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  flutter_timezone: ^4.1.0

  # Salvar configurações do usuário
  shared_preferences: ^2.5.3


flutter:
  uses-material-design: true
